---
title:               Chris Burnor
tagline:             Professional Nerd
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Chris Burnor
twitter:             chrisburnor
about_me:            about-me
email:               self@chrisburnor.com
google_analytics_id: UA-29146404-1
disqus_shortname:    <%= ENV.fetch("disqus_shortname") { "" } %>
